export const emotionPackData = [{
    "id": 1,
    "name": "中表情",
    "cover": "",
    "type": 1,
    "isValid": 0,
    "packVersion": 1,
    "analyVersion": 3,
    "order": 4,
    "extra": 1
  },
  {
    "id": 2,
    "name": "天气",
    "cover": "",
    "type": 0,
    "isValid": 1,
    "packVersion": 1,
    "analyVersion": 1,
    "order": 3,
    "extra": 2
  },
  {
    "id": 3,
    "name": "中表情",
    "cover": "",
    "type": 1,
    "isValid": 0,
    "packVersion": 1,
    "analyVersion": 3,
    "order": 4,
    "extra": 1
  },
  {
    "id": 4,
    "name": "天气",
    "cover": "",
    "type": 0,
    "isValid": 1,
    "packVersion": 1,
    "analyVersion": 1,
    "order": 3,
    "extra": 2
  },
  {
    "id": 5,
    "name": "中表情",
    "cover": "",
    "type": 1,
    "isValid": 0,
    "packVersion": 1,
    "analyVersion": 3,
    "order": 4,
    "extra": 1
  },
  {
    "id": 6,
    "name": "天气",
    "cover": "",
    "type": 0,
    "isValid": 1,
    "packVersion": 1,
    "analyVersion": 1,
    "order": 3,
    "extra": 2
  },
  {
    "id": 7,
    "name": "中表情",
    "cover": "",
    "type": 1,
    "isValid": 0,
    "packVersion": 1,
    "analyVersion": 3,
    "order": 4,
    "extra": 1
  },
  {
    "id": 8,
    "name": "天气",
    "cover": "",
    "type": 0,
    "isValid": 1,
    "packVersion": 1,
    "analyVersion": 1,
    "order": 3,
    "extra": 2
  },
  {
    "id": 9,
    "name": "中表情",
    "cover": "",
    "type": 1,
    "isValid": 0,
    "packVersion": 1,
    "analyVersion": 3,
    "order": 4,
    "extra": 1
  },
  {
    "id": 10,
    "name": "天气",
    "cover": "",
    "type": 0,
    "isValid": 1,
    "packVersion": 1,
    "analyVersion": 1,
    "order": 3,
    "extra": 2
  },
  {
    "id": 11,
    "name": "中表情",
    "cover": "",
    "type": 1,
    "isValid": 0,
    "packVersion": 1,
    "analyVersion": 3,
    "order": 4,
    "extra": 1
  },
  {
    "id": 12,
    "name": "天气",
    "cover": "",
    "type": 0,
    "isValid": 1,
    "packVersion": 1,
    "analyVersion": 1,
    "order": 3,
    "extra": 2
  }
];

export const emotionData = [{
    "id": 1,
    "name": "捂脸",
    "cover": "",
    "order": 1,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 2,
    "name": "捂脸",
    "cover": "",
    "order": 2,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 3,
    "name": "捂脸",
    "cover": "",
    "order": 1,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 42,
    "name": "捂脸",
    "cover": "",
    "order": 2,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 4,
    "name": "捂脸",
    "cover": "",
    "order": 1,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 12,
    "name": "捂脸",
    "cover": "",
    "order": 2,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 5,
    "name": "捂脸",
    "cover": "",
    "order": 1,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 23,
    "name": "捂脸",
    "cover": "",
    "order": 2,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 6,
    "name": "捂脸",
    "cover": "",
    "order": 1,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 24,
    "name": "捂脸",
    "cover": "",
    "order": 2,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 7,
    "name": "捂脸",
    "cover": "",
    "order": 1,
    "extra": 1,
    "width": 20,
    "height": 20,
  },
  {
    "id": 25,
    "name": "捂脸",
    "cover": "",
    "order": 2,
    "extra": 1,
    "width": 20,
    "height": 20,
  }
];

export const giftData = [{
    "giftId": 1,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 2,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  },
  {
    "giftId": 3,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 4,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  },
  {
    "giftId": 5,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 6,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  },
  {
    "giftId": 7,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 8,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  },
  {
    "giftId": 9,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 21,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  },
  {
    "giftId": 122,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 23,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  },
  {
    "giftId": 31,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 24,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  },
  {
    "giftId": 41,
    "name": "帐篷",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 10,
    "addPrice": 10,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 1
  },
  {
    "giftId": 25,
    "name": "飞机",
    "image": "",
    "imageWidth": 10,
    "imageHeight": 10,
    "price": 1000,
    "addPrice": 200,
    "gifImage": "",
    "duration": 10000,
    "sortNumber": 2
  }
];

export const lotteryData = [{
    "topicId": 145,
    "topicName": "勿忘我",
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 0
  },
  {
    "topicId": 1451,
    "topicName": "快乐家族",
    "lotteryId": 134,
    "lotteryName": "谁是快乐家族",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 1
  },
  {
    "topicId": 1452,
    "topicName": "勿忘我",
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 0
  },
  {
    "topicId": 1453,
    "topicName": "快乐家族",
    "lotteryId": 134,
    "lotteryName": "谁是快乐家族",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 1
  },
  {
    "topicId": 1454,
    "topicName": "勿忘我",
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 0
  },
  {
    "topicId": 1455,
    "topicName": "快乐家族",
    "lotteryId": 134,
    "lotteryName": "谁是快乐家族",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 1
  },
  {
    "topicId": 1456,
    "topicName": "勿忘我",
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 0
  },
  {
    "topicId": 1457,
    "topicName": "快乐家族",
    "lotteryId": 134,
    "lotteryName": "谁是快乐家族",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 1
  },
  {
    "topicId": 1458,
    "topicName": "勿忘我",
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 0
  },
  {
    "topicId": 1459,
    "topicName": "快乐家族",
    "lotteryId": 134,
    "lotteryName": "谁是快乐家族",
    "createdAt": 1511078400000,
    "validAt": 1511078400000,
    "status": 1
  }
];

export const lotteryUserData = [{
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "小小女",
    "userId": 13452,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 1,
    "invitationNum": 133
  },
  {
    "lotteryId": 124,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "龙女",
    "userId": 13344,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 0,
    "invitationNum": 13
  },
  {
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "小小女",
    "userId": 134521,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 1,
    "invitationNum": 133
  },
  {
    "lotteryId": 124,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "龙女",
    "userId": 133441,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 0,
    "invitationNum": 13
  },
  {
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "小小女",
    "userId": 134522,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 1,
    "invitationNum": 133
  },
  {
    "lotteryId": 124,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "龙女",
    "userId": 133442,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 0,
    "invitationNum": 13
  },
  {
    "lotteryId": 234,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "小小女",
    "userId": 134523,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 1,
    "invitationNum": 133
  },
  {
    "lotteryId": 124,
    "lotteryName": "勿思勿念诗成篇",
    "userNick": "龙女",
    "userId": 133443,
    "joinTime": 1511078400000,
    "status": 0,
    "isAppoint": 0,
    "invitationNum": 13
  }
];


